JTR-143-funciones-de-agrupado
janis-commerce/solr pull request #21
Opened 2022-04-05 20:53 UTC by Nataniel4

**LINK AL TICKET**
https://fizzmod.atlassian.net/browse/JTR-143

**LINK A LA HISTORIA**
https://fizzmod.atlassian.net/browse/JTR-142

**DESCRIPCIÓN DEL REQUERIMIENTO**
- Agregar metodos de agrupado, usar https://solr.apache.org/guide/6_6/result-grouping.html como referencia

**DESCRIPCIÓN DE LA SOLUCIÓN**
- Se agregaron dos metodos:
  - `group`: Para agrupar resultados por campo o campos
  - `facet`: Para obtener el conteo de items por campo, o campos combinados

**CÓMO SE PUEDE PROBAR**
⚠️ Esto ya fue super probado en un Solr corriendo en local, se puede hacer lo mismo si aun asi queres probarlo.
![imagen](https://user-images.githubusercontent.com/19476574/161846812-13f0037e-3f06-4ed9-bf5e-e2d102b703a8.png)

Eso es todo amigos 🚪🏃

2022-04-08 12:13 UTC, KarenEchavarria commented on README.md
> +Get facet counts by field or pivot
Sería bueno tener una pequeña definición de pivot, porque no queda muy clara a simple vista la diferencia con field como para poder determinar cuál se usa

2022-04-11 13:38 UTC, Nataniel4 commented on lib/helpers/query.js
> +		const {
Quedo así porque algunas propiedades las saca desde el params porque crea variables con el mismo nombre pero segun lo que haya en params

2022-04-11 13:44 UTC, Nataniel4 commented on README.md
> +Get facet counts by field or pivot
Lo explique lo mejor que pude con los ejemplos y con como devuelve los datos segun como envies ese param, no pude encontrar mejor manera de explicarlo
<img width="603" alt="image" src="https://user-images.githubusercontent.com/19476574/162752885-b052bc81-0d4a-44f6-a58a-5e44329c78a8.png">
<img width="636" alt="image" src="https://user-images.githubusercontent.com/19476574/162752927-4483417b-d4d1-48bf-9b53-8cb312c14bf2.png">

2022-04-12 13:27 UTC, KarenEchavarria approved these changes

2022-05-04 14:16 UTC, mdanelutti commented on lib/helpers/query.js
> +		const filters = params.filters ? { filter: Filters.build(params.filters, fields) } : {};
retruco un poco lo que comenta Karen por un lado sumar `order` y `filters` al destructuring y omitir instanciar filters y order, y hacerlo directo en el objeto del return

`return {
	query: '*:*',
	offset: (page * limit) - limit,
	limit,
	params: {
		facet: true,
		...field && { 'facet.field': field },
		...pivot && { 'facet.pivot': pivot }
	},
	...filters && { filter: Filters.build(filters, fields) },
	...order && { sort: this._getSorting(order) }
};`

esta lógica puede aplicar de igual forma para `group()`

Opción 2: tener un método que genere `filters` y `order` entonces lo que es `Filters.build()` y `this._getSorting()` lo tenes en un solo lugar, terminando en algo así como, `...orderAndFilter(params)` en el return

2022-05-04 14:23 UTC, mdanelutti commented on lib/helpers/response.js
> +			});
acá un opcional, podes hacer que sea un reduce y asignarlo directo en `groups`

2022-05-04 14:27 UTC, mdanelutti commented on lib/solr.js
> +		const page = params.page || 1;
si tenemos `DEFAULT_LIMIT` y `DEFAULT_GROUP_LIMIT`, por que no tenemos `DEFAULT_START_PAGE`? 😜

2022-05-04 14:31 UTC, mdanelutti requested changes
hay dos cosas opcionales y un cambio mínimo

2022-05-04 18:43 UTC, Nataniel4 commented on lib/helpers/response.js
> +			});
Me parecio re mercenario meter un reduce dentro de un reduce si igual tengo que asignar la data al acumulador del reduce principal 😭

2022-05-11 23:08 UTC, mdanelutti approved these changes

2022-05-17 12:50 UTC, merged